version: "2.24"

services:
  kafka:
    build:
      context: ./
    container_name: kafka-server
    ports:
      - "9092:9092"   # for external clients
      - "9093:9093" # internal Docker use (optional to expose)		
    volumes:
      - kafka-data:/opt/kafka/data
  
      
  #ruby-pdf:
  #  build:
  #    context: ./ruby-pdf/
  #  container_name: ruby-pdf
  #  depends_on:
  #    - kafka
  #  environment: 
  #    KAFKA_BROKERS: kafka:29092
  #  volumes:
  #    - ./ruby-pdf:/app
  #  working_dir: /app
  #  command: ["wait-for-it", "kafka:29092", "--", "bundle", "exec", "karafka", "server"]

volumes:
  kafka-data: