version: "2.24"

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka-1
    ports:
      - 9092:9092
      - 9091:9091
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://localhost:9093,INTERNAL_PLAINTEXT://kafka:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL_PLAINTEXT://kafka:9091
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL_PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  ruby-pdf:
    build:
      context: ./ruby-pdf/
    container_name: ruby-pdf
    depends_on:
      - kafka
    environment: 
      KAFKA_ADVERTISED_LISTENER: kafka:9091
    volumes:
      - ./ruby-pdf:/app
    working_dir: /app
    command: ["wait-for-it", "kafka:9091", "--", "bundle", "exec", "karafka", "server"]

volumes:
  kafka-data: